### ISSUE TITLE
Make `ProductionFromMapEdge` work with units other than aircraft

### ISSUE THREAD

**Issue by obrakmann** [obrakmann/openra-wargame#2]

**Comment by ABrandau** [comment]
![production](https://cloud.githubusercontent.com/assets/11763228/11640930/20e725ee-9d14-11e5-876f-d62e66d42d4d.gif)
![fact](https://cloud.githubusercontent.com/assets/11763228/11640931/20f00d6c-9d14-11e5-9368-40a549dc7363.gif)
It works but the units created ignore the terrain, and also won't leave the factory by themselves, won't a support power could work better for this case? Say, a paradrop support power, that creates a selectable unit from the edge of the map, that just moves to the destination selected by the player?

**Comment by obrakmann** [comment]
Yeah, that's what I meant with "make it work with". `ProductionFromMapEdge` currently does stupid things. Not sure if there is a reason for that. It also doesn't make use of rallypoints at all. But it's all easy to fix (except for one thing, finding an appropriate edge cell to spawn from).

**Comment by obrakmann** [comment]
Fixed by https://github.com/OpenRA/OpenRA/pull/10851
